language: cpp

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:andykimpe/cmake
  - sudo apt-get -qq update
  - sudo apt-get install -y freeglut3-dev libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get -qq install g++-4.8 gcc-4.8
  - sudo apt-get -qq install cmake
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - ./tools/scripts/install-test-deps.sh

script: make release

os:
  - linux
