language: cpp
os: linux
sudo: required
dist: trusty

before_script:
  - sudo add-apt-repository -y ppa:andykimpe/cmake
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake
  - tools/scripts/vulkan-deps.sh

fast_finish: true

env:
  - CMD=cppcheck
  - CMD=unittest TYPE=debug BACKEND=gles2
  - CMD=unittest TYPE=debug BACKEND=vulkan
  - CMD=unittest TYPE=debug BACKEND=software
  - CMD=build TYPE=release BACKEND=gles2
  - CMD=build TYPE=debug BACKEND=gles2
  - CMD=build TYPE=release BACKEND=vulkan
  - CMD=build TYPE=debug BACKEND=vulkan
  - CMD=build TYPE=release BACKEND=software
  - CMD=build TYPE=debug BACKEND=software
  - CMD=build ARGS="--examples"

addons:
  apt:
    packages:
      - cppcheck
      - freeglut3-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev

cache:
  directories:
    - tools/frameworks

script:
  - tools/scripts/travis.sh

